vich_uploader:
    db_driver: orm

    mappings:
        event_image:
            uri_prefix: /assets/images/events
            upload_destination: '%kernel.project_dir%/public/assets/images/events'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        picture_image:
            uri_prefix: /assets/images/pictures
            upload_destination: '%kernel.project_dir%/public/assets/images/pictures'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        product_image:
            uri_prefix: /assets/images/products
            upload_destination: '%kernel.project_dir%/public/assets/images/products'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
