vich_uploader:
    db_driver: orm

    mappings:
        user_image:
            uri_prefix: /assets/images/users
            upload_destination: '%kernel.project_dir%/public/assets/images/users'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        event_image:
            uri_prefix: /assets/images/events
            upload_destination: '%kernel.project_dir%/public/assets/images/events'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        picture_image:
            uri_prefix: /assets/images/picture
            upload_destination: '%kernel.project_dir%/public/assets/images/picture'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        product_image:
            uri_prefix: /assets/images/products
            upload_destination: '%kernel.project_dir%/public/assets/images/products'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
